### PR TITLE
VATRP-2199: Not registering when WiFi Only is selected

### PR DESCRIPTION
**Pull request by Semrubo**

### CODE REVIEW

**Comment by zackm0571** [comment]
iPhone 6 Verizon iOS v8.3: When WiFi only is selected, the user can still make calls over 4G even though status is unregistered and WiFi is not connected.

**Comment by kennethdick** [comment]
This is a bigger question, should we disable registration so calls cant be received or also put logic to prevent outbound calls? The apps do allow outbound call attempts even when not registered. This might be a useless question because it is up to the server to reject the unregistered source call

**Comment by zackm0571** [comment]
I don't think we have properly unregistered if we can make / receive calls. Additionally, this defeats the purpose of using WiFi only.

**Comment by kennethdick** [comment]
Make call is not the same as receive calls. Did you test that you could
receive call after turning wifi-only on and disabling your wifi?

**Comment by kennethdick** [comment]
Retest with acetest registrar. STL lets unregistered users make calls

**Comment by zackm0571** [comment]
Confirmed working on acetest. Good call.

**Comment by zackm0571** [comment]
+1

**Pull request merged**
