### PR TITLE
VATRP-3126: Fix crash on iOS 7 hangup

### PR DESCRIPTION
**Pull request by zackm0571**

### CODE REVIEW

**Comment by kennethdick** [comment]
Also VATRP-3124

**Comment by kennethdick** [comment]
This must be tested on iOS8 and iOS9 thoroughly before being merged. The UI changes are larger enough to be concerned for compatibility. iOS7 is much less used

**Comment by kennethdick** [comment]
+1

**Comment by shareefalis** [comment]
Just to warn you enabling zombies can makes bad things happen. Silent crashes and stuff like that can happen.

**Pull request merged**
