### PR TITLE
Ianblenke/reconverge upstream

### PR DESCRIPTION
**Pull request by ianblenke**
This rectifies upstream with shareef un-reverted PR #306.

Note: I'm building this now, it isn't ready to merge until I've tested it locally.

### CODE REVIEW

**Comment by shareefalis** [comment]
+1  you can probably ignore kif framework that is just a test framework like calabash

**Comment by zackm0571** [comment]
+1

**Comment by ianblenke** [comment]
This now works with respectable video quality. 

The fix was this:

https://github.com/VTCSecureLLC/msopenh264/commit/201ed16e4d9f22fb1c135454c47008ebe85fe9eb

In submodules/msopenh264/src/msopenh264enc.cpp

```
params.bEnableAdaptiveQuant = false
```

When this is set to true, we get the gradual fade to blur around fingers. With this set to false, this does not happen.

**Comment by zackm0571** [comment]
+1

**Comment by ladyhawk** [comment]
+1

**Pull request merged**
