### PR TITLE
Vatrp 2951: Add functionality to export all contacts.

### PR DESCRIPTION
**Pull request by Semrubo**

### CODE REVIEW

**Comment by zackm0571** [comment]
Tested locally and did not receive contacts in attachment. iPhone 6 verizon iOS 8.3

**Comment by kennethdick** [comment]
Was the bulk export failure due to missing sip addresses? or phone numbers? We need this fixed and ready for Tuesday

**Comment by Semrubo** [comment]
Done some corrections. The reason was the contacts without phone number(s) . 
Tested on iPad mini and iPhone 6s

**Comment by patrickmwatson** [comment]
-1 Not receiving attachment see attached.
ios all contacts export

**Comment by Semrubo** [comment]
I see that vCard attachment exists in your email, then the sending process problem can be the phone OS or simulator issue.

**Comment by kennethdick** [comment]
+1

**Pull request merged**
