### PR TITLE
VATRP-3493: Prevent chat bubbles overlapping text.

### PR DESCRIPTION
**Pull request by zackm0571**

### CODE REVIEW

**Comment by shareefalis** [comment]
+1

**Comment by ladyhawk** [comment]
Zack - I will happily +1with the adjustment to the font size value that i sent : )

**Comment by zackm0571** [comment]
@ladyhawk good call. Thanks for that one.

**Comment by ladyhawk** [comment]
+1 +1 +1  -- NICE!

**Pull request merged**
