### PR TITLE
VATRP-1087: Color picker impl

### PR DESCRIPTION
**Pull request by zackm0571**

### CODE REVIEW

**Comment by shareefalis** [comment]
Why remove the submodule for colorpicker?

**Comment by zackm0571** [comment]
Their upstream has too much legacy code. We don't want to be reliant on anymore code bases at this point. Omnitor said they used the same code base for one of their projects. They said just copy it locally, do your modifications, and decouple with the remote master.

**Comment by kennethdick** [comment]
+1

**Comment by patrickmwatson** [comment]
+1

**Pull request merged**
