### PR TITLE
Just your usual merge from belledonne.

### PR DESCRIPTION
**Pull request by shareefalis**

### CODE REVIEW

**Comment by shareefalis** [comment]
Still failing to build here..

**Comment by shareefalis** [comment]
+1 merge after it is built

**Comment by shareefalis** [comment]
I would rather hold this off because this is still an ongoing fix.

**Comment by shareefalis** [comment]
I recommend we merge this friday morning,

**Comment by shareefalis** [comment]
https://vtcsecure.atlassian.net/browse/VATRP-567

**Comment by ianblenke** [comment]
VATRP-567 is about enabling Bitcode for XCode.

Belledonne says they can't reproduce this problem with their upstream builds of linphone-iphone.

I'd feel more comfortable understanding exactly what it is that we are fixing here, and how.

**Comment by shareefalis** [comment]
Build passes and it look good to me. need someone to code review

**Comment by kennethdick** [comment]
+1 LGTM

**Pull request merged**
